### ISSUE TITLE
Display list of todo's 

### ISSUE THREAD

**Issue by justyna-strach** [justyna-strach/todo-list-react#2]
**Issue description:**
- [ ]  add records to mock database
- [ ] display data in GUI
- [ ] add tests cases
