### ISSUE TITLE
Create todo

### ISSUE THREAD

**Issue by justyna-strach** [justyna-strach/todo-list-react#3]
**Issue description:**
- [ ]  create some panel in GUI to adding items
- [ ]  add creating todo functionality
- [ ]  add tests cases
